### ISSUE TITLE
Implement initial ruleset umbrella ☂️

### ISSUE THREAD

**Issue by jedrichards** [sketch-hq/sketch-assistant-core-rules#14]
Umbrella issue for implementing initial ruleset. It may be sensible to firm up the rule architecture a bit before diving into these (e.g. sketch-hq/sketch-lint#1 and https://github.com/BohemianCoding/sketch-file-format/issues/9)

- [x] `images-no-outsized` sketch-hq/sketch-lint-ruleset-core#13 
- [x] `artboards-layout` sketch-hq/sketch-lint-ruleset-core#12 
- [x] `artboards-grid` sketch-hq/sketch-lint-ruleset-core#11 
- [x] `borders-no-disabled` sketch-hq/sketch-lint-ruleset-core#10 
- [x] `groups-no-empty` sketch-hq/sketch-lint-ruleset-core#9
- [x] `layers-no-subpixel-positioning` sketch-hq/sketch-lint-ruleset-core#8 
- [x] `styles-no-unused` sketch-hq/sketch-lint-ruleset-core#7
- [x] `groups-no-redundant` sketch-hq/sketch-lint-ruleset-core#6 
- [x] `styles-no-duplicate` sketch-hq/sketch-lint-ruleset-core#5 
- [x] `layer-names-pattern-allowed` sketch-hq/sketch-lint-ruleset-core#4 
- [x] `layers-no-hidden` sketch-hq/sketch-lint-ruleset-core#3 
- [x] `groups-max-layers` sketch-hq/sketch-lint-ruleset-core#2 
- [x] `symbols-no-unused` sketch-hq/sketch-lint-ruleset-core#1
